<?php namespace Meliblue\ElasticBlue\Models;


use Meliblue\Models\CleanNode;

class ElasticNodeCache extends ElasticNode
{

    protected static $index = 'nodes-cache';
    protected static $type = "node-cache";
    private static $maxRelations = 30;
    public $relationTypes = [];
    public $nodeTypes = [];


    public function setNode(CleanNode $node)
    {
        parent::setNode($node); // TODO: Change the autogenerated stub

        foreach ($node->relationTypes as $rel) {
            $rel->relations['in'] = array_slice($rel->relations['in'], 0, static::$maxRelations);
            $rel->relations['out'] = array_slice($rel->relations['out'], 0, static::$maxRelations);
        }
        $this->relationTypes = $node->relationTypes;
        $this->nodeTypes = $node->nodeTypes;
    }
}